// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file provides a Go HTTP client library for the inventory API.
// Generated from: pkg/codegen/templates/client.go.tmpl
//
// To modify the client:
//  1. Edit the template file: pkg/codegen/templates/client.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated client methods for each resource:
//   - GetResources(ctx) - List all resources
//   - GetResource(ctx, uid) - Get specific resource by UID
//   - CreateResource(ctx, req) - Create new resource
//   - UpdateResource(ctx, uid, req) - Update existing resource
//   - DeleteResource(ctx, uid) - Delete resource
//
// Usage example:
//
//	client, err := client.NewClient("http://localhost:8080", nil)
//	if err != nil {
//	    log.Fatal(err)
//	}
//
//	bmcs, err := client.GetBMCs(context.Background())
//	if err != nil {
//	    log.Fatal(err)
//	}
//
// To add authentication:
//  1. Create custom http.Client with auth transport
//  2. Pass it to NewClient:
//     httpClient := &http.Client{
//     Transport: &AuthTransport{Token: "your-token"},
//     }
//     client, _ := client.NewClient(baseURL, httpClient)
//
// To add custom headers:
//  1. Modify doRequest method to accept header options
//  2. Or wrap http.Client with custom RoundTripper
//
// To handle retries:
//  1. Wrap http.Client with retry transport
//  2. Use github.com/hashicorp/go-retryablehttp or similar
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"github.com/example/fru-service/pkg/resources/connection"
	"github.com/example/fru-service/pkg/resources/device"
	"github.com/example/fru-service/pkg/resources/fru"
	"github.com/example/fru-service/pkg/resources/location"
	"io"
	"net/http"
	"net/url"
	"path"
)

// Client provides access to the inventory API
type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
	version    string // Optional API version for Accept/Content-Type headers
}

// ErrorResponse represents an API error response
type ErrorResponse struct {
	Error string `json:"error"`
}

// NewClient creates a new API client
func NewClient(baseURL string, httpClient *http.Client) (*Client, error) {
	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	u, err := url.Parse(baseURL)
	if err != nil {
		return nil, fmt.Errorf("invalid base URL: %w", err)
	}

	return &Client{
		baseURL:    u,
		httpClient: httpClient,
	}, nil
}

// WithVersion returns a new client configured to use a specific API version
func (c *Client) WithVersion(version string) *Client {
	return &Client{
		baseURL:    c.baseURL,
		httpClient: c.httpClient,
		version:    version,
	}
}

// doRequest performs an HTTP request and handles the response
func (c *Client) doRequest(ctx context.Context, method, endpoint string, body interface{}, result interface{}) error {
	var reqBody io.Reader
	if body != nil {
		jsonData, err := json.Marshal(body)
		if err != nil {
			return fmt.Errorf("failed to marshal request body: %w", err)
		}
		reqBody = bytes.NewBuffer(jsonData)
	}

	u := *c.baseURL
	u.Path = path.Join(u.Path, endpoint)

	req, err := http.NewRequestWithContext(ctx, method, u.String(), reqBody)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}

	// Set Content-Type and Accept headers with optional version
	contentType := "application/json"
	acceptType := "application/json"
	if c.version != "" {
		contentType = fmt.Sprintf("application/json;version=%s", c.version)
		acceptType = fmt.Sprintf("application/json;version=%s", c.version)
	}

	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	req.Header.Set("Accept", acceptType)

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("request failed: %w", err)
	}
	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		var errorResp ErrorResponse
		if err := json.Unmarshal(respBody, &errorResp); err != nil {
			return fmt.Errorf("HTTP error %d: %s", resp.StatusCode, string(respBody))
		}
		return fmt.Errorf("API error (%d): %s", resp.StatusCode, errorResp.Error)
	}

	if result != nil {
		if err := json.Unmarshal(respBody, result); err != nil {
			return fmt.Errorf("failed to unmarshal response: %w", err)
		}
	}

	return nil
}

// GetFRUs retrieves all frus
func (c *Client) GetFRUs(ctx context.Context) ([]fru.FRU, error) {
	var response []fru.FRU
	if err := c.doRequest(ctx, "GET", "/frus", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetFRU retrieves a specific FRU by UID
func (c *Client) GetFRU(ctx context.Context, uid string) (*fru.FRU, error) {
	var result fru.FRU
	endpoint := fmt.Sprintf("/frus/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateFRU creates a new FRU
func (c *Client) CreateFRU(ctx context.Context, req CreateFRURequest) (*fru.FRU, error) {
	var result fru.FRU
	if err := c.doRequest(ctx, "POST", "/frus", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateFRU updates an existing FRU
func (c *Client) UpdateFRU(ctx context.Context, uid string, req UpdateFRURequest) (*fru.FRU, error) {
	var result fru.FRU
	endpoint := fmt.Sprintf("/frus/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteFRU deletes a FRU by UID
func (c *Client) DeleteFRU(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/frus/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetDevices retrieves all devices
func (c *Client) GetDevices(ctx context.Context) ([]device.Device, error) {
	var response []device.Device
	if err := c.doRequest(ctx, "GET", "/devices", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetDevice retrieves a specific Device by UID
func (c *Client) GetDevice(ctx context.Context, uid string) (*device.Device, error) {
	var result device.Device
	endpoint := fmt.Sprintf("/devices/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateDevice creates a new Device
func (c *Client) CreateDevice(ctx context.Context, req CreateDeviceRequest) (*device.Device, error) {
	var result device.Device
	if err := c.doRequest(ctx, "POST", "/devices", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateDevice updates an existing Device
func (c *Client) UpdateDevice(ctx context.Context, uid string, req UpdateDeviceRequest) (*device.Device, error) {
	var result device.Device
	endpoint := fmt.Sprintf("/devices/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteDevice deletes a Device by UID
func (c *Client) DeleteDevice(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/devices/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetLocations retrieves all locations
func (c *Client) GetLocations(ctx context.Context) ([]location.Location, error) {
	var response []location.Location
	if err := c.doRequest(ctx, "GET", "/locations", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetLocation retrieves a specific Location by UID
func (c *Client) GetLocation(ctx context.Context, uid string) (*location.Location, error) {
	var result location.Location
	endpoint := fmt.Sprintf("/locations/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateLocation creates a new Location
func (c *Client) CreateLocation(ctx context.Context, req CreateLocationRequest) (*location.Location, error) {
	var result location.Location
	if err := c.doRequest(ctx, "POST", "/locations", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateLocation updates an existing Location
func (c *Client) UpdateLocation(ctx context.Context, uid string, req UpdateLocationRequest) (*location.Location, error) {
	var result location.Location
	endpoint := fmt.Sprintf("/locations/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteLocation deletes a Location by UID
func (c *Client) DeleteLocation(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/locations/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}

// GetConnections retrieves all connections
func (c *Client) GetConnections(ctx context.Context) ([]connection.Connection, error) {
	var response []connection.Connection
	if err := c.doRequest(ctx, "GET", "/connections", nil, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// GetConnection retrieves a specific Connection by UID
func (c *Client) GetConnection(ctx context.Context, uid string) (*connection.Connection, error) {
	var result connection.Connection
	endpoint := fmt.Sprintf("/connections/%s", uid)
	if err := c.doRequest(ctx, "GET", endpoint, nil, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// CreateConnection creates a new Connection
func (c *Client) CreateConnection(ctx context.Context, req CreateConnectionRequest) (*connection.Connection, error) {
	var result connection.Connection
	if err := c.doRequest(ctx, "POST", "/connections", req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// UpdateConnection updates an existing Connection
func (c *Client) UpdateConnection(ctx context.Context, uid string, req UpdateConnectionRequest) (*connection.Connection, error) {
	var result connection.Connection
	endpoint := fmt.Sprintf("/connections/%s", uid)
	if err := c.doRequest(ctx, "PUT", endpoint, req, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

// DeleteConnection deletes a Connection by UID
func (c *Client) DeleteConnection(ctx context.Context, uid string) error {
	endpoint := fmt.Sprintf("/connections/%s", uid)
	var response DeleteResponse
	if err := c.doRequest(ctx, "DELETE", endpoint, nil, &response); err != nil {
		return err
	}
	return nil
}
