// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains client-side request/response models.
// Generated from: pkg/codegen/templates/client-models.go.tmpl
//
// To modify client models:
//  1. Edit the template file: pkg/codegen/templates/client-models.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// DEPRECATED: This template is a legacy stub. The actual client models are
// generated in models.go.tmpl and used by both server and client.
//
// Generated request types:
//   - CreateResourceRequest: Create operation with metadata
//   - UpdateResourceRequest: Update operation with partial fields
//   - DeleteResponse: Confirmation of deletion
//
// Note: This file contains TODO comments indicating that resource-specific
// fields should be added. Consider migrating to the unified models.go.tmpl
// approach or implementing spec field embedding.
//
// To implement full spec support:
//  1. Import resource packages
//  2. Embed ResourceSpec in request structs
//  3. Use json:",inline" tag for proper serialization
//
// To add validation:
//  1. Add validate tags (e.g., validate:"required,min=3")
//  2. Use go-playground/validator in client before sending
package client

import (
	"github.com/example/fru-service/pkg/resources/connection"
	"github.com/example/fru-service/pkg/resources/device"
	"github.com/example/fru-service/pkg/resources/fru"
	"github.com/example/fru-service/pkg/resources/location"
)

// CreateFRURequest represents a request to create a FRU
type CreateFRURequest struct {
	fru.FRUSpec `json:",inline"`
	Name        string            `json:"name" validate:"required"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// UpdateFRURequest represents a request to update a FRU
type UpdateFRURequest struct {
	fru.FRUSpec `json:",inline,omitempty"`
	Name        string            `json:"name,omitempty"`
	Labels      map[string]string `json:"labels,omitempty"`
	Annotations map[string]string `json:"annotations,omitempty"`
}

// CreateDeviceRequest represents a request to create a Device
type CreateDeviceRequest struct {
	device.DeviceSpec `json:",inline"`
	Name              string            `json:"name" validate:"required"`
	Labels            map[string]string `json:"labels,omitempty"`
	Annotations       map[string]string `json:"annotations,omitempty"`
}

// UpdateDeviceRequest represents a request to update a Device
type UpdateDeviceRequest struct {
	device.DeviceSpec `json:",inline,omitempty"`
	Name              string            `json:"name,omitempty"`
	Labels            map[string]string `json:"labels,omitempty"`
	Annotations       map[string]string `json:"annotations,omitempty"`
}

// CreateLocationRequest represents a request to create a Location
type CreateLocationRequest struct {
	location.LocationSpec `json:",inline"`
	Name                  string            `json:"name" validate:"required"`
	Labels                map[string]string `json:"labels,omitempty"`
	Annotations           map[string]string `json:"annotations,omitempty"`
}

// UpdateLocationRequest represents a request to update a Location
type UpdateLocationRequest struct {
	location.LocationSpec `json:",inline,omitempty"`
	Name                  string            `json:"name,omitempty"`
	Labels                map[string]string `json:"labels,omitempty"`
	Annotations           map[string]string `json:"annotations,omitempty"`
}

// CreateConnectionRequest represents a request to create a Connection
type CreateConnectionRequest struct {
	connection.ConnectionSpec `json:",inline"`
	Name                      string            `json:"name" validate:"required"`
	Labels                    map[string]string `json:"labels,omitempty"`
	Annotations               map[string]string `json:"annotations,omitempty"`
}

// UpdateConnectionRequest represents a request to update a Connection
type UpdateConnectionRequest struct {
	connection.ConnectionSpec `json:",inline,omitempty"`
	Name                      string            `json:"name,omitempty"`
	Labels                    map[string]string `json:"labels,omitempty"`
	Annotations               map[string]string `json:"annotations,omitempty"`
}

// DeleteResponse represents a successful deletion response
type DeleteResponse struct {
	Message string `json:"message"`
	UID     string `json:"uid"`
}
