// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/fru-service/internal/storage/ent/label"
	"github.com/example/fru-service/internal/storage/ent/predicate"
	"github.com/example/fru-service/internal/storage/ent/resource"
)

// LabelUpdate is the builder for updating Label entities.
type LabelUpdate struct {
	config
	hooks    []Hook
	mutation *LabelMutation
}

// Where appends a list predicates to the LabelUpdate builder.
func (lu *LabelUpdate) Where(ps ...predicate.Label) *LabelUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetKey sets the "key" field.
func (lu *LabelUpdate) SetKey(s string) *LabelUpdate {
	lu.mutation.SetKey(s)
	return lu
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (lu *LabelUpdate) SetNillableKey(s *string) *LabelUpdate {
	if s != nil {
		lu.SetKey(*s)
	}
	return lu
}

// SetValue sets the "value" field.
func (lu *LabelUpdate) SetValue(s string) *LabelUpdate {
	lu.mutation.SetValue(s)
	return lu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (lu *LabelUpdate) SetNillableValue(s *string) *LabelUpdate {
	if s != nil {
		lu.SetValue(*s)
	}
	return lu
}

// SetResourceID sets the "resource" edge to the Resource entity by ID.
func (lu *LabelUpdate) SetResourceID(id int) *LabelUpdate {
	lu.mutation.SetResourceID(id)
	return lu
}

// SetResource sets the "resource" edge to the Resource entity.
func (lu *LabelUpdate) SetResource(r *Resource) *LabelUpdate {
	return lu.SetResourceID(r.ID)
}

// Mutation returns the LabelMutation object of the builder.
func (lu *LabelUpdate) Mutation() *LabelMutation {
	return lu.mutation
}

// ClearResource clears the "resource" edge to the Resource entity.
func (lu *LabelUpdate) ClearResource() *LabelUpdate {
	lu.mutation.ClearResource()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LabelUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LabelUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LabelUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LabelUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LabelUpdate) check() error {
	if v, ok := lu.mutation.Key(); ok {
		if err := label.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Label.key": %w`, err)}
		}
	}
	if v, ok := lu.mutation.Value(); ok {
		if err := label.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Label.value": %w`, err)}
		}
	}
	if lu.mutation.ResourceCleared() && len(lu.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Label.resource"`)
	}
	return nil
}

func (lu *LabelUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(label.Table, label.Columns, sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Key(); ok {
		_spec.SetField(label.FieldKey, field.TypeString, value)
	}
	if value, ok := lu.mutation.Value(); ok {
		_spec.SetField(label.FieldValue, field.TypeString, value)
	}
	if lu.mutation.ResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{label.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LabelUpdateOne is the builder for updating a single Label entity.
type LabelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LabelMutation
}

// SetKey sets the "key" field.
func (luo *LabelUpdateOne) SetKey(s string) *LabelUpdateOne {
	luo.mutation.SetKey(s)
	return luo
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (luo *LabelUpdateOne) SetNillableKey(s *string) *LabelUpdateOne {
	if s != nil {
		luo.SetKey(*s)
	}
	return luo
}

// SetValue sets the "value" field.
func (luo *LabelUpdateOne) SetValue(s string) *LabelUpdateOne {
	luo.mutation.SetValue(s)
	return luo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (luo *LabelUpdateOne) SetNillableValue(s *string) *LabelUpdateOne {
	if s != nil {
		luo.SetValue(*s)
	}
	return luo
}

// SetResourceID sets the "resource" edge to the Resource entity by ID.
func (luo *LabelUpdateOne) SetResourceID(id int) *LabelUpdateOne {
	luo.mutation.SetResourceID(id)
	return luo
}

// SetResource sets the "resource" edge to the Resource entity.
func (luo *LabelUpdateOne) SetResource(r *Resource) *LabelUpdateOne {
	return luo.SetResourceID(r.ID)
}

// Mutation returns the LabelMutation object of the builder.
func (luo *LabelUpdateOne) Mutation() *LabelMutation {
	return luo.mutation
}

// ClearResource clears the "resource" edge to the Resource entity.
func (luo *LabelUpdateOne) ClearResource() *LabelUpdateOne {
	luo.mutation.ClearResource()
	return luo
}

// Where appends a list predicates to the LabelUpdate builder.
func (luo *LabelUpdateOne) Where(ps ...predicate.Label) *LabelUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LabelUpdateOne) Select(field string, fields ...string) *LabelUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Label entity.
func (luo *LabelUpdateOne) Save(ctx context.Context) (*Label, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LabelUpdateOne) SaveX(ctx context.Context) *Label {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LabelUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LabelUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LabelUpdateOne) check() error {
	if v, ok := luo.mutation.Key(); ok {
		if err := label.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Label.key": %w`, err)}
		}
	}
	if v, ok := luo.mutation.Value(); ok {
		if err := label.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Label.value": %w`, err)}
		}
	}
	if luo.mutation.ResourceCleared() && len(luo.mutation.ResourceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Label.resource"`)
	}
	return nil
}

func (luo *LabelUpdateOne) sqlSave(ctx context.Context) (_node *Label, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(label.Table, label.Columns, sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Label.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, label.FieldID)
		for _, f := range fields {
			if !label.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != label.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Key(); ok {
		_spec.SetField(label.FieldKey, field.TypeString, value)
	}
	if value, ok := luo.mutation.Value(); ok {
		_spec.SetField(label.FieldValue, field.TypeString, value)
	}
	if luo.mutation.ResourceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.ResourceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   label.ResourceTable,
			Columns: []string{label.ResourceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Label{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{label.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
