// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/example/fru-service/internal/storage/ent/annotation"
	"github.com/example/fru-service/internal/storage/ent/label"
	"github.com/example/fru-service/internal/storage/ent/resource"
)

// ResourceCreate is the builder for creating a Resource entity.
type ResourceCreate struct {
	config
	mutation *ResourceMutation
	hooks    []Hook
}

// SetUID sets the "uid" field.
func (rc *ResourceCreate) SetUID(s string) *ResourceCreate {
	rc.mutation.SetUID(s)
	return rc
}

// SetName sets the "name" field.
func (rc *ResourceCreate) SetName(s string) *ResourceCreate {
	rc.mutation.SetName(s)
	return rc
}

// SetAPIVersion sets the "api_version" field.
func (rc *ResourceCreate) SetAPIVersion(s string) *ResourceCreate {
	rc.mutation.SetAPIVersion(s)
	return rc
}

// SetNillableAPIVersion sets the "api_version" field if the given value is not nil.
func (rc *ResourceCreate) SetNillableAPIVersion(s *string) *ResourceCreate {
	if s != nil {
		rc.SetAPIVersion(*s)
	}
	return rc
}

// SetKind sets the "kind" field.
func (rc *ResourceCreate) SetKind(s string) *ResourceCreate {
	rc.mutation.SetKind(s)
	return rc
}

// SetResourceType sets the "resource_type" field.
func (rc *ResourceCreate) SetResourceType(s string) *ResourceCreate {
	rc.mutation.SetResourceType(s)
	return rc
}

// SetSpec sets the "spec" field.
func (rc *ResourceCreate) SetSpec(jm json.RawMessage) *ResourceCreate {
	rc.mutation.SetSpec(jm)
	return rc
}

// SetStatus sets the "status" field.
func (rc *ResourceCreate) SetStatus(jm json.RawMessage) *ResourceCreate {
	rc.mutation.SetStatus(jm)
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *ResourceCreate) SetCreatedAt(t time.Time) *ResourceCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *ResourceCreate) SetNillableCreatedAt(t *time.Time) *ResourceCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetUpdatedAt sets the "updated_at" field.
func (rc *ResourceCreate) SetUpdatedAt(t time.Time) *ResourceCreate {
	rc.mutation.SetUpdatedAt(t)
	return rc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (rc *ResourceCreate) SetNillableUpdatedAt(t *time.Time) *ResourceCreate {
	if t != nil {
		rc.SetUpdatedAt(*t)
	}
	return rc
}

// SetResourceVersion sets the "resource_version" field.
func (rc *ResourceCreate) SetResourceVersion(s string) *ResourceCreate {
	rc.mutation.SetResourceVersion(s)
	return rc
}

// SetNillableResourceVersion sets the "resource_version" field if the given value is not nil.
func (rc *ResourceCreate) SetNillableResourceVersion(s *string) *ResourceCreate {
	if s != nil {
		rc.SetResourceVersion(*s)
	}
	return rc
}

// SetNamespace sets the "namespace" field.
func (rc *ResourceCreate) SetNamespace(s string) *ResourceCreate {
	rc.mutation.SetNamespace(s)
	return rc
}

// SetNillableNamespace sets the "namespace" field if the given value is not nil.
func (rc *ResourceCreate) SetNillableNamespace(s *string) *ResourceCreate {
	if s != nil {
		rc.SetNamespace(*s)
	}
	return rc
}

// AddLabelIDs adds the "labels" edge to the Label entity by IDs.
func (rc *ResourceCreate) AddLabelIDs(ids ...int) *ResourceCreate {
	rc.mutation.AddLabelIDs(ids...)
	return rc
}

// AddLabels adds the "labels" edges to the Label entity.
func (rc *ResourceCreate) AddLabels(l ...*Label) *ResourceCreate {
	ids := make([]int, len(l))
	for i := range l {
		ids[i] = l[i].ID
	}
	return rc.AddLabelIDs(ids...)
}

// AddAnnotationIDs adds the "annotations" edge to the Annotation entity by IDs.
func (rc *ResourceCreate) AddAnnotationIDs(ids ...int) *ResourceCreate {
	rc.mutation.AddAnnotationIDs(ids...)
	return rc
}

// AddAnnotations adds the "annotations" edges to the Annotation entity.
func (rc *ResourceCreate) AddAnnotations(a ...*Annotation) *ResourceCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return rc.AddAnnotationIDs(ids...)
}

// Mutation returns the ResourceMutation object of the builder.
func (rc *ResourceCreate) Mutation() *ResourceMutation {
	return rc.mutation
}

// Save creates the Resource in the database.
func (rc *ResourceCreate) Save(ctx context.Context) (*Resource, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ResourceCreate) SaveX(ctx context.Context) *Resource {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ResourceCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ResourceCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *ResourceCreate) defaults() {
	if _, ok := rc.mutation.APIVersion(); !ok {
		v := resource.DefaultAPIVersion
		rc.mutation.SetAPIVersion(v)
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := resource.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		v := resource.DefaultUpdatedAt()
		rc.mutation.SetUpdatedAt(v)
	}
	if _, ok := rc.mutation.ResourceVersion(); !ok {
		v := resource.DefaultResourceVersion
		rc.mutation.SetResourceVersion(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ResourceCreate) check() error {
	if _, ok := rc.mutation.UID(); !ok {
		return &ValidationError{Name: "uid", err: errors.New(`ent: missing required field "Resource.uid"`)}
	}
	if v, ok := rc.mutation.UID(); ok {
		if err := resource.UIDValidator(v); err != nil {
			return &ValidationError{Name: "uid", err: fmt.Errorf(`ent: validator failed for field "Resource.uid": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Resource.name"`)}
	}
	if v, ok := rc.mutation.Name(); ok {
		if err := resource.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Resource.name": %w`, err)}
		}
	}
	if _, ok := rc.mutation.APIVersion(); !ok {
		return &ValidationError{Name: "api_version", err: errors.New(`ent: missing required field "Resource.api_version"`)}
	}
	if _, ok := rc.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "Resource.kind"`)}
	}
	if v, ok := rc.mutation.Kind(); ok {
		if err := resource.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Resource.kind": %w`, err)}
		}
	}
	if _, ok := rc.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "Resource.resource_type"`)}
	}
	if v, ok := rc.mutation.ResourceType(); ok {
		if err := resource.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "Resource.resource_type": %w`, err)}
		}
	}
	if _, ok := rc.mutation.Spec(); !ok {
		return &ValidationError{Name: "spec", err: errors.New(`ent: missing required field "Resource.spec"`)}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Resource.created_at"`)}
	}
	if _, ok := rc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Resource.updated_at"`)}
	}
	if _, ok := rc.mutation.ResourceVersion(); !ok {
		return &ValidationError{Name: "resource_version", err: errors.New(`ent: missing required field "Resource.resource_version"`)}
	}
	return nil
}

func (rc *ResourceCreate) sqlSave(ctx context.Context) (*Resource, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ResourceCreate) createSpec() (*Resource, *sqlgraph.CreateSpec) {
	var (
		_node = &Resource{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(resource.Table, sqlgraph.NewFieldSpec(resource.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.UID(); ok {
		_spec.SetField(resource.FieldUID, field.TypeString, value)
		_node.UID = value
	}
	if value, ok := rc.mutation.Name(); ok {
		_spec.SetField(resource.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := rc.mutation.APIVersion(); ok {
		_spec.SetField(resource.FieldAPIVersion, field.TypeString, value)
		_node.APIVersion = value
	}
	if value, ok := rc.mutation.Kind(); ok {
		_spec.SetField(resource.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := rc.mutation.ResourceType(); ok {
		_spec.SetField(resource.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := rc.mutation.Spec(); ok {
		_spec.SetField(resource.FieldSpec, field.TypeJSON, value)
		_node.Spec = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(resource.FieldStatus, field.TypeJSON, value)
		_node.Status = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.SetField(resource.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := rc.mutation.UpdatedAt(); ok {
		_spec.SetField(resource.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := rc.mutation.ResourceVersion(); ok {
		_spec.SetField(resource.FieldResourceVersion, field.TypeString, value)
		_node.ResourceVersion = value
	}
	if value, ok := rc.mutation.Namespace(); ok {
		_spec.SetField(resource.FieldNamespace, field.TypeString, value)
		_node.Namespace = value
	}
	if nodes := rc.mutation.LabelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.LabelsTable,
			Columns: []string{resource.LabelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(label.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.AnnotationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   resource.AnnotationsTable,
			Columns: []string{resource.AnnotationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(annotation.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ResourceCreateBulk is the builder for creating many Resource entities in bulk.
type ResourceCreateBulk struct {
	config
	err      error
	builders []*ResourceCreate
}

// Save creates the Resource entities in the database.
func (rcb *ResourceCreateBulk) Save(ctx context.Context) ([]*Resource, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Resource, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ResourceCreateBulk) SaveX(ctx context.Context) []*Resource {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ResourceCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ResourceCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
