// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Connection resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /connections (list all connections)
//   - GET /connections/{uid} (get specific Connection)
//   - POST /connections (create new Connection)
//   - PUT /connections/{uid} (update Connection)
//   - DELETE /connections/{uid} (delete Connection)
//
// Authentication: DISABLED
// Storage: Uses storage.LoadConnection*/SaveConnection*/DeleteConnection*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/connection/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadConnectionWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/alexlovelltroy/fabrica/pkg/resource"
	"github.com/alexlovelltroy/fabrica/pkg/validation"
	"github.com/alexlovelltroy/fabrica/pkg/versioning"
	"github.com/example/fru-service/internal/storage"
	"github.com/example/fru-service/pkg/resources/connection"
	"github.com/go-chi/chi/v5"
)

// GetConnections returns all Connection resources
func GetConnections(w http.ResponseWriter, r *http.Request) {

	connections, err := storage.LoadAllConnections(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load connections: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, connections)
}

// GetConnection returns a specific Connection resource by UID
func GetConnection(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Connection UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadConnection() with version-aware function

	connection, err := storage.LoadConnection(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Connection not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, connection)
}

// CreateConnection creates a new Connection resource
func CreateConnection(w http.ResponseWriter, r *http.Request) {
	var req CreateConnectionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Connection")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	connection := &connection.Connection{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "Connection",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.ConnectionSpec,
	}

	connection.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		connection.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		connection.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(connection); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), connection); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveConnection(r.Context(), connection); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Connection: %w", err))
		return
	}

	respondJSON(w, http.StatusCreated, connection)
}

// UpdateConnection updates an existing Connection resource
func UpdateConnection(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Connection UID is required"))
		return
	}

	connection, err := storage.LoadConnection(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Connection not found: %w", err))
		return
	}

	var req UpdateConnectionRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		connection.SetName(req.Name)
	}

	// Update spec fields - merge non-zero values from request
	connection.Spec = req.ConnectionSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		connection.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		connection.SetAnnotation(k, v)
	}

	connection.Touch()

	if err := storage.SaveConnection(r.Context(), connection); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Connection: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, connection)
}

// DeleteConnection deletes a Connection resource
func DeleteConnection(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Connection UID is required"))
		return
	}

	if err := storage.DeleteConnection(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Connection: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Connection deleted successfully",
		UID:     uid,
	})
}
