// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Device resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /devices (list all devices)
//   - GET /devices/{uid} (get specific Device)
//   - POST /devices (create new Device)
//   - PUT /devices/{uid} (update Device)
//   - DELETE /devices/{uid} (delete Device)
//
// Authentication: DISABLED
// Storage: Uses storage.LoadDevice*/SaveDevice*/DeleteDevice*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/device/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadDeviceWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/alexlovelltroy/fabrica/pkg/resource"
	"github.com/alexlovelltroy/fabrica/pkg/validation"
	"github.com/alexlovelltroy/fabrica/pkg/versioning"
	"github.com/example/fru-service/internal/storage"
	"github.com/example/fru-service/pkg/resources/device"
	"github.com/go-chi/chi/v5"
)

// GetDevices returns all Device resources
func GetDevices(w http.ResponseWriter, r *http.Request) {

	devices, err := storage.LoadAllDevices(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load devices: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, devices)
}

// GetDevice returns a specific Device resource by UID
func GetDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadDevice() with version-aware function

	device, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, device)
}

// CreateDevice creates a new Device resource
func CreateDevice(w http.ResponseWriter, r *http.Request) {
	var req CreateDeviceRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Device")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	device := &device.Device{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "Device",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.DeviceSpec,
	}

	device.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		device.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		device.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(device); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), device); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveDevice(r.Context(), device); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Device: %w", err))
		return
	}

	respondJSON(w, http.StatusCreated, device)
}

// UpdateDevice updates an existing Device resource
func UpdateDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	device, err := storage.LoadDevice(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Device not found: %w", err))
		return
	}

	var req UpdateDeviceRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		device.SetName(req.Name)
	}

	// Update spec fields - merge non-zero values from request
	device.Spec = req.DeviceSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		device.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		device.SetAnnotation(k, v)
	}

	device.Touch()

	if err := storage.SaveDevice(r.Context(), device); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Device: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, device)
}

// DeleteDevice deletes a Device resource
func DeleteDevice(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Device UID is required"))
		return
	}

	if err := storage.DeleteDevice(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Device: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Device deleted successfully",
		UID:     uid,
	})
}
