// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API handlers for Location resources.
// Generated from: pkg/codegen/templates/handlers.go.tmpl
//
// To modify this code:
//  1. Edit the template file: pkg/codegen/templates/handlers.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// Generated handlers provide:
//   - GET /locations (list all locations)
//   - GET /locations/{uid} (get specific Location)
//   - POST /locations (create new Location)
//   - PUT /locations/{uid} (update Location)
//   - DELETE /locations/{uid} (delete Location)
//
// Authentication: DISABLED
// Storage: Uses storage.LoadLocation*/SaveLocation*/DeleteLocation*
// Version Support: Available (see version context in handlers)
//
// To enable full version conversion for this resource:
//  1. Create v2beta1 package: pkg/resources/location/v2beta1/
//  2. Implement converter: v2beta1/converter.go
//  3. Add version-aware storage: storage.LoadLocationWithVersion()
//  4. Register versions in cmd/server/main.go
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/alexlovelltroy/fabrica/pkg/resource"
	"github.com/alexlovelltroy/fabrica/pkg/validation"
	"github.com/alexlovelltroy/fabrica/pkg/versioning"
	"github.com/example/fru-service/internal/storage"
	"github.com/example/fru-service/pkg/resources/location"
	"github.com/go-chi/chi/v5"
)

// GetLocations returns all Location resources
func GetLocations(w http.ResponseWriter, r *http.Request) {

	locations, err := storage.LoadAllLocations(r.Context())
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to load locations: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, locations)
}

// GetLocation returns a specific Location resource by UID
func GetLocation(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Location UID is required"))
		return
	}

	// Version context available here for version-aware operations
	// versionCtx := versioning.GetVersionContext(r.Context())
	// Requested version: versionCtx.ServeVersion
	// To enable: replace storage.LoadLocation() with version-aware function

	location, err := storage.LoadLocation(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Location not found: %w", err))
		return
	}
	respondJSON(w, http.StatusOK, location)
}

// CreateLocation creates a new Location resource
func CreateLocation(w http.ResponseWriter, r *http.Request) {
	var req CreateLocationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Get version context from request
	versionCtx := versioning.GetVersionContext(r.Context())

	uid, err := resource.GenerateUIDForResource("Location")
	if err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to generate UID: %w", err))
		return
	}

	location := &location.Location{
		Resource: resource.Resource{
			APIVersion:    versionCtx.GroupVersion,
			Kind:          "Location",
			SchemaVersion: versionCtx.ServeVersion,
		},
		Spec: req.LocationSpec,
	}

	location.Metadata.Initialize(req.Name, uid)

	// Set labels and annotations
	for k, v := range req.Labels {
		location.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		location.SetAnnotation(k, v)
	}

	// Layer 2: Fabrica struct tag validation
	if err := validation.ValidateResource(location); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Layer 3: Custom business logic validation
	if err := validation.ValidateWithContext(r.Context(), location); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("validation failed: %w", err))
		return
	}

	// Set initial status

	// Save (Layer 1: Ent validation happens automatically if using Ent storage)
	if err := storage.SaveLocation(r.Context(), location); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Location: %w", err))
		return
	}

	respondJSON(w, http.StatusCreated, location)
}

// UpdateLocation updates an existing Location resource
func UpdateLocation(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Location UID is required"))
		return
	}

	location, err := storage.LoadLocation(r.Context(), uid)
	if err != nil {
		respondError(w, http.StatusNotFound, fmt.Errorf("Location not found: %w", err))
		return
	}

	var req UpdateLocationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		respondError(w, http.StatusBadRequest, fmt.Errorf("invalid request body: %w", err))
		return
	}

	// Apply updates
	if req.Name != "" {
		location.SetName(req.Name)
	}

	// Update spec fields - merge non-zero values from request
	location.Spec = req.LocationSpec

	// Update labels and annotations
	for k, v := range req.Labels {
		location.SetLabel(k, v)
	}
	for k, v := range req.Annotations {
		location.SetAnnotation(k, v)
	}

	location.Touch()

	if err := storage.SaveLocation(r.Context(), location); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to save Location: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, location)
}

// DeleteLocation deletes a Location resource
func DeleteLocation(w http.ResponseWriter, r *http.Request) {
	uid := chi.URLParam(r, "uid")
	if uid == "" {
		respondError(w, http.StatusBadRequest, fmt.Errorf("Location UID is required"))
		return
	}

	if err := storage.DeleteLocation(r.Context(), uid); err != nil {
		respondError(w, http.StatusInternalServerError, fmt.Errorf("failed to delete Location: %w", err))
		return
	}

	respondJSON(w, http.StatusOK, &DeleteResponse{
		Message: "Location deleted successfully",
		UID:     uid,
	})
}
