// Code generated by codegen. DO NOT EDIT.
// Copyright © 2025 OpenCHAMI a Series of LF Projects, LLC
//
// SPDX-License-Identifier: MIT
//
// This file contains REST API route registrations for all resources.
// Generated from: pkg/codegen/templates/routes.go.tmpl
//
// To modify route registration:
//  1. Edit the template file: pkg/codegen/templates/routes.go.tmpl
//  2. Run 'make dev' to regenerate
//  3. Do NOT edit this file directly - changes will be lost
//
// This file registers routes for all resource types:
//   - /frus (FRU operations)
//   - /devices (Device operations)
//   - /locations (Location operations)
//   - /connections (Connection operations)
//
// Route patterns:
//   - GET    /resource       -> List all resources
//   - GET    /resource/{uid} -> Get specific resource
//   - POST   /resource       -> Create new resource
//   - PUT    /resource/{uid} -> Update resource
//   - DELETE /resource/{uid} -> Delete resource
//
// To add middleware to routes:
//  1. Apply middleware in cmd/server/main.go before calling RegisterGeneratedRoutes
//  2. Use r.Use() calls in main.go, not in generated route functions
//
// To add custom routes:
//  1. Create a separate RegisterCustomRoutes function
//  2. Call it after RegisterGeneratedRoutes in main.go
package main

import (
	"github.com/go-chi/chi/v5"
)

// RegisterGeneratedRoutes registers all generated routes
// Note: Middleware should be applied in main.go before calling this function
func RegisterGeneratedRoutes(r chi.Router) {

	// FRU routes
	r.Route("/frus", func(r chi.Router) {
		r.Get("/", GetFRUs)
		r.Post("/", CreateFRU)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetFRU)
			r.Put("/", UpdateFRU)
			r.Delete("/", DeleteFRU)
		})
	})

	// Device routes
	r.Route("/devices", func(r chi.Router) {
		r.Get("/", GetDevices)
		r.Post("/", CreateDevice)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetDevice)
			r.Put("/", UpdateDevice)
			r.Delete("/", DeleteDevice)
		})
	})

	// Location routes
	r.Route("/locations", func(r chi.Router) {
		r.Get("/", GetLocations)
		r.Post("/", CreateLocation)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetLocation)
			r.Put("/", UpdateLocation)
			r.Delete("/", DeleteLocation)
		})
	})

	// Connection routes
	r.Route("/connections", func(r chi.Router) {
		r.Get("/", GetConnections)
		r.Post("/", CreateConnection)
		r.Route("/{uid}", func(r chi.Router) {
			r.Get("/", GetConnection)
			r.Put("/", UpdateConnection)
			r.Delete("/", DeleteConnection)
		})
	})

	// OpenAPI documentation routes
	r.Get("/openapi.json", ServeOpenAPISpec)
	r.Get("/docs", ServeSwaggerUI)
}
